### ISSUE TITLE
Create Fake Bolt service to make end-to-end testing possible in dev ENVs

### ISSUE THREAD

**Issue by SergeyKutsko** [SergeyKutsko/universal_auto#10]
The fake service should be a part of a current Django application, and it should mimic the original, so we can run the report the same way as on production and receive a report. 

Authentication page with login and password can be copied from https://fleets.bolt.eu/login

Here are weekly and daily report pages:

[Archive 2.zip](https://github.com/SergeyKutsko/universal_auto/files/9638039/Archive.2.zip)
[Archive.zip](https://github.com/SergeyKutsko/universal_auto/files/9638040/Archive.zip)

**Comment by SergeyKutsko** [comment]
Authentication page with login and password can be copied from https://fleets.bolt.eu/login

**Comment by busterskh** [comment]
Візьму це завдання. Чи є якесь ТЗ до нього? Або можливо є приклад особистого кабінету та функціоналу?

**Comment by SergeyKutsko** [comment]
> Візьму це завдання. Чи є якесь ТЗ до нього? Або можливо є приклад особистого кабінету та функціоналу?

Для початку зробіть сторінку донина яка вказана в описі

**Comment by IvanPryvedenets** [comment]
Візьму це завдання.

**Comment by Mytiaiev** [comment]
@busterskh @IvanPryvedenets  шановні, як успіхи з завданям?

**Comment by busterskh** [comment]
Маю проблему з запуском Postgres. @SergeyKutsko логи додаю. Можливо зможете допомогти.
![Снимок экрана 2022-09-28 в 14 23 59](https://user-images.githubusercontent.com/99525773/193294826-b7a50dc8-c604-415f-9e07-8c3d84fe8553.png)
![Снимок экрана 2022-09-28 в 14 24 36](https://user-images.githubusercontent.com/99525773/193294833-b2d5ec08-4490-4d77-a01e-57890942e16d.png)

**Comment by busterskh** [comment]
@Mytiaiev готовий логін, але досі не бачив що у сособистому кабінеті коїтся. Зловив проблему за Postgres

**Comment by Mytiaiev** [comment]
> @Mytiaiev готовий логін, але досі не бачив що у сособистому кабінеті коїтся. Зловив проблему за Postgres

як я розумію основний функціонал там сторинка логіна, та сторинка з якої можно зробити витяг репорту, фото репорту та path є в додатку до 4 issues

**Comment by dholova** [comment]
Візьму це завдання

**Comment by KurochkaR** [comment]
> > Візьму це завдання. Чи є якесь ТЗ до нього? Або можливо є приклад особистого кабінету та функціоналу?
> 
> Для початку зробіть сторінку логіна яка вказана в описі щоб в неї можливо логінитися та вона показувала помилку якщо пароль не вірний https://fleets.bolt.eu/login

потрібен тільки логін без реєстрації чи повний функціонал? при успішному логіні перенаправляти повинно також на дубльовану сторінку bolt з  якої тягнемо репорт? @SergeyKutsko

**Comment by dholova** [comment]
Вітаю! Не зовсім зрозуміло, що робити після створення сторінки з логіном. Підкажіть, будь ласка, у якому форматі повинна виглядати програма?

**Comment by SergeyKutsko** [comment]
Клон оригинального сервісу

**Comment by dholova** [comment]
Вітаю, підкажіть, можливо є якийсь фейковий акаунт, щоб зрозуміти, як виглядає сайт всередині? Тому що сервіс ніяк не підтверде мою регістрацію. html файл показує таку сторінку, а при спробі натиснути на будь-яку кнопку чи звіт, вибиває сайт з реєстрацією. Чи потрібно зробити просто сторінку "home" з цими кнопками без подальшого розвитку?
![image](https://user-images.githubusercontent.com/103906556/222458400-e762a846-ba7d-46e0-a9cb-4731df04e0bf.png)

**Comment by KurochkaR** [comment]
Я правильно розумію selenium бере репорт з оригіналу, зберігає в бд а нам портібно витягнути репорт з бд юзеру на клоні? @SergeyKutsko
