### ISSUE TITLE
Make telegram bot using Webhooks event via Django instead of poling loop process. 

### ISSUE THREAD

**Issue by SergeyKutsko** [SergeyKutsko/universal_auto#103]
In order to scale out app we need make using Webhooks.

**Comment by OlegBondarUA** [comment]
Візьму це завдання.

**Comment by OlegBondarUA** [comment]
підскажіть яку версію python-telegram-bot використовуєте?

**Comment by SergeyKutsko** [comment]
python-telegram-bot==13.13

**Comment by OlegBondarUA** [comment]
https://github.com/OlegBondarUA/Telegram-webhook/tree/main/webhook

я зробив тестове завдання

**Comment by OlegBondarUA** [comment]
добрий день сидів тиа зрозумів шо зробив не так 
я клонував репо та створив гілку issues-103-bondar
тепер я так розумію мені потрібно там зробити тестове.

є питання що саме я маю з тим webhook зробити? 
зробити шоб webhook з telegram bot надходив на адрес django в моєму випадку на локал хост? @SergeyKutsko
