### ISSUE TITLE
Report_of_driver_debt

### ISSUE THREAD

**Issue by SpaceIgor** [SergeyKutsko/universal_auto#107]
- create a preview image in the admin panel for Report_of_driver_debt and view and viewing pictures outside the admin panel
- redesign the functionality in the bot so that the image is stored in a separate folder reports/reports_of_driver_debt
- write unittest for this function in bot  and pytest for model

**Comment by KurochkaR** [comment]
viewing pictures outside the admin panel what does it mean?
