### ISSUE TITLE
Bug. After creating a driver with an identical chat id, all the buttons for the chat bot work are missing.

### ISSUE THREAD

**Issue by WARGDOOM** [SergeyKutsko/universal_auto#109]
Description:
1. I am creating a new Driver with chat id    920945954
2. Assign chat id 920945954 to another driver
3. The buttons for working with the chat bot disappear.
4. When deleting a driver with the same chat id, the functionality of the buttons appears, but we should never delete drivers from the database
<img width="1455" alt="Снимок экрана 2023-02-16 в 17 25 35" src="https://user-images.githubusercontent.com/125297683/219419645-f09c87dc-6a9c-42dc-9600-2897c205d783.png">
<img width="1455" alt="Снимок экрана 2023-02-16 в 17 26 35" src="https://user-images.githubusercontent.com/125297683/219419678-df91d5ab-1879-41ec-9dc0-a74d04180b2d.png">

**Comment by SpaceIgor** [comment]
@WARGDOOM I told you. Chat_id is its unique value. We don't have two drivers with the same chat id. Its not bug. And this functionality in the images for the user (client).
and
