### ISSUE TITLE
Develop Privat24 Selenium bot to make possible auto-pay to driver via telegram from Universal UAH card of fleet owner after weekly salary confirmed by driver and manager 

### ISSUE THREAD

**Issue by SergeyKutsko** [SergeyKutsko/universal_auto#11]
You need implement Class which can login https://next.privat24.ua/ with phone number 

<img width="1129" alt="Снимок экрана 2022-09-29 в 08 58 16" src="https://user-images.githubusercontent.com/424550/192950977-06c6845e-f168-4c11-a3c0-353c10b4d571.png">

Create virtual card for tests you can transfer money between your cards  for test purposes

Please use https://next.privat24.ua/money-transfer/card functionality to accomplish card to card transfers. 

So your Selenium class should Accept phone number and pass for login , can wait for 2 factor auth confirmed by phone owner. It should transfer money from Fleet Owner card to Driver's so amount to transfer and driver crd should be input param for your Class.

**Comment by pythogoras** [comment]
завдання цікаве. може візьму якщо знайду інше рішення. зарезервувати можно?

**Comment by SergeyKutsko** [comment]
ok

**Comment by romankot** [comment]
Будь ласка додайте детальні вимоги та аксептанс критерії

**Comment by SergeyKutsko** [comment]
@romankot @pythogoras Updated description.

**Comment by SpaceIgor** [comment]
i take it
