### ISSUE TITLE
Order taxi from landing page and fix logo icon and wording on a page 

### ISSUE THREAD

**Issue by SergeyKutsko** [SergeyKutsko/universal_auto#112]
We are live now by https://ninja-taxi.kyiv.ua/

we need make that page look customer ready and add ability order taxi via landing page form and add subscription form for future service subscription.

**Comment by KurochkaR** [comment]
Візьму це завдання, я правильно зрозумів, треба підключити форми для ордеру та підписки на сторінці?

**Comment by KurochkaR** [comment]
Є питання по ордеру у формі є 4 поля , в моделі інші поля, це будуть різні моделі, якщо ні то що робити з полями які лишились; що саме треба змінити у формулюванні на сторінці @SergeyKutsko

**Comment by SergeyKutsko** [comment]
> Візьму це завдання, я правильно зрозумів, для початку, треба підключити форми для ордеру та підписки на сторінці?

так

**Comment by SergeyKutsko** [comment]
> Є питання по ордеру у формі є 4 поля , в моделі інші поля, це будуть різні моделі, якщо ні то що робити з полями які лишились; що саме треба змінити у формулюванні на сторінці @SergeyKutsko

можно використовувати поля моделі - форма повина бути зменшена до 2 полів - номер телефона та pick up location

**Comment by KurochkaR** [comment]
Ще маленьке уточнення. Як перевіряти правильність адреси в замовленні та по телефону +380777777777 80555555555 0953433333 380347777777 це все вірні номери чи потрібно певний формат? @SergeyKutsko

**Comment by SpaceIgor** [comment]
> Ще маленькі уточнення. Як перевіряти правильність адреси в замовленні; та питання по телефону +380777777777 80555555555 0953433333 380347777777 це все вірні номери чи потрібно певний формат? @SergeyKutsko

в моделі user є функція валідації на номер телефона залежно від прийнятої довжини номера, на виході повертає кажись +380...... якщо не вдалось обробити то значення None

**Comment by SergeyKutsko** [comment]
Так треба 1 формат
Вт, 21 февр. 2023 г. в 20:46, Igor ***@***.***>:
