### ISSUE TITLE
The menu /status_car function "fit for service" does not work anymore after entering the car number

### ISSUE THREAD

**Issue by WARGDOOM** [SergeyKutsko/universal_auto#118]
<img width="1047" alt="Снимок экрана 2023-02-20 в 18 08 40" src="https://user-images.githubusercontent.com/125297683/220155185-3c8d056f-b69e-4627-8fdc-a2086b420f4d.png">
When starting the /status_car menu, the "serviceable" function after entering the car number no longer shows the status that should have been assigned to the car in the chatbot and in the database and administration

**Comment by SpaceIgor** [comment]
done
