### ISSUE TITLE
DB tables doesn't appears after migration script run 

### ISSUE THREAD

**Issue by romankot** [SergeyKutsko/universal_auto#19]
The same reproduced on Windows 10 and macOS BigSur
Steps to reproduce 
1. docker-compose up --build
2. docker exec -it universal_auto_web_1 python manage.py migrate
3. Connect to Postgres db with "universal_auto_dev" user
Expected result: tables are present 
Actual result:
checking on pgadmin there are no tables 
screenshot [https://ibb.co/bX2xbNQ](url)

Connections details [https://ibb.co/tbhxgpX](url)

**Comment by SergeyKutsko** [comment]
@romankot it is fixed, pull new develop and follow new README.md

Thanks for reporting!
