### ISSUE TITLE
Create drivers rating page and send same rating to all drivers via telegram message each week on Monday and each month on first Monday of new month.

### ISSUE THREAD

**Issue by SergeyKutsko** [SergeyKutsko/universal_auto#22]
We need show list of drivers and trips count per fleet and sorted by total amount of money per week.

**Comment by bogdannoff** [comment]
I would like to work on this

**Comment by SergeyKutsko** [comment]
@bogdannoff ok

**Comment by bogdannoff** [comment]
@SergeyKutsko, i`ve made a pull request but can`t select reviewers
