### ISSUE TITLE
add pages on site

### ISSUE THREAD

**Issue by KurochkaR** [SergeyKutsko/universal_auto#359]
need page for investor, manager, partner dashboard
add page for discover partner functionality

**Comment by SergeyKutsko** [comment]
@OlegBondarUA

**Comment by OlegBondarUA** [comment]
1. Створюємо обліковий запис та присвоюємо йому групу "інвестор".
2. Створюємо інвестора (у нашій системі адміністрування) та додаємо його до облікового запису, який ми створили.
3. Прикріплюємо автомобіль до інвестора.
4. Здійснюємо декілька витрат для цього автомобіля (за бажанням).
5. Заходимо на веб-сайт та виконуємо вхід як інвестор (нас перенаправляє на інвестиційну панель).

**Comment by OlegBondarUA** [comment]
зроблено: need page for investor, manager, partner dashboard, add page for discover partner functionality

перенос на інший тікет: add page for discover children drive, Work with Alina on design.
