### ISSUE TITLE
Add ability to look statistics by day via telegram command

### ISSUE THREAD

**Issue by SergeyKutsko** [SergeyKutsko/universal_auto#4]

**Comment by Mytiaiev** [comment]
We need bot, what upon request <dd.mm.yyyy> in telegram chat, response log from DB?

**Comment by SergeyKutsko** [comment]
Bot is already here. We need implementation of command . Which will return result per Role. Driver have only his statistics for given day. Manager will get all drivers statistics assigned to him. Owner role will get statistics for all his cars and drivers.

**Comment by SergeyKutsko** [comment]
You will get data from DB if it is already in db, but you need get missing data from Uber Uklon or Bolt report for that day

**Comment by Mytiaiev** [comment]
authentication by role after OTP code gives automatically or need extra foo to auth role?

**Comment by SergeyKutsko** [comment]
Yes, we need to allow seeing statistics only per Role and Permissions. So one driver can't see other driver statistics. And this statistic is different for Manager and Fleet owner as well.

**Comment by Mytiaiev** [comment]
its start from foo report/get_report? or separate new foo

**Comment by SergeyKutsko** [comment]
@Mytiaiev you need to implement separate command for day reporting, look in DB first, but if it's missing need go Uber, Uklon, Bolt and get it to DB first.

**Comment by SerheyShtepa** [comment]
Taking this task.

**Comment by SerheyShtepa** [comment]
Where can I find the bot's source code?

**Comment by SergeyKutsko** [comment]
> Where can I find the bot's source code?

Scripts/bot.pay

**Comment by OleksiiKH0240** [comment]
i take this task

**Comment by SergeyKutsko** [comment]
@Mytiaiev @OleksiiKH0240 @SerheyShtepa  this task is dependent on Fake apps, since we need ability to load report by day

**Comment by SergeyKutsko** [comment]
Ось як дістати репорт за 1 день з Убера

[20220926-20220927-payments_order-___.csv](https://github.com/SergeyKutsko/universal_auto/files/9652057/20220926-20220927-payments_order-___.csv)
<img width="1791" alt="Screenshot 2022-09-27 at 08 56 52" src="https://user-images.githubusercontent.com/424550/192444619-5a680b69-1ae6-4164-9f13-bef890ec40c4.png">

**Comment by SergeyKutsko** [comment]
Ось як це виглядає в Болт
<img width="1791" alt="Screenshot 2022-09-27 at 08 59 06" src="https://user-images.githubusercontent.com/424550/192445094-4055ab2d-417a-492a-b5e2-6e11cb026f00.png">
[Щоденний звіт Bolt – 26.09.2022 – Kyiv Fleet 03_232 park Universal-auto.csv](https://github.com/SergeyKutsko/universal_auto/files/9652080/Bolt.26.09.2022.Kyiv.Fleet.03_232.park.Universal-auto.csv)

**Comment by SergeyKutsko** [comment]
Уклон

<img width="1791" alt="Screenshot 2022-09-27 at 09 02 08" src="https://user-images.githubusercontent.com/424550/192445418-e38fb800-ce26-4301-b186-5c49a9f5b664.png">

**Comment by Mytiaiev** [comment]
@SergeyKutsko я так розумию єто функція download_payments_order та save_report в silenium tools чи надо добавити нову.

**Comment by VeronyWise** [comment]
я тоді приєднююсь команди з 4 завдання, так як говорили на зустрічі сьогодні, і 3 завдання теж постараємось зробити)

**Comment by SergeyKutsko** [comment]
@Mytiaiev this function pulls weekly report, you can adjust it to pull by given day only 

@VeronyWise OK

**Comment by SpaceIgor** [comment]
i take this task
