### ISSUE TITLE
Create script  to Download and save to DB all available information from reports of Uber, Uklon, Bolt 

### ISSUE THREAD

**Issue by SergeyKutsko** [SergeyKutsko/universal_auto#46]

**Comment by alex2011ua** [comment]
I take this issue

**Comment by alex2011ua** [comment]
as I understand first of all I should do this methods 
https://github.com/SergeyKutsko/universal_auto/blob/3405fbf81b4896ed986519c5946b978a88f17c74/scripts/bot.py#L54
https://github.com/SergeyKutsko/universal_auto/blob/3405fbf81b4896ed986519c5946b978a88f17c74/scripts/bot.py#L56
https://github.com/SergeyKutsko/universal_auto/blob/3405fbf81b4896ed986519c5946b978a88f17c74/scripts/bot.py#L58
