### ISSUE TITLE
Get all uniq transactions from Uber, Uklon, Bolt and save to database 

### ISSUE THREAD

**Issue by SergeyKutsko** [SergeyKutsko/universal_auto#5]
You need get all customer payments of trips from Uber, Ukon, Bolt reports or HTML UI.

Currently only bolt has transactions as a part of weekly report, 
Uber have a diff report with all transactions will attach to repo as well

Uklon need to be investigated how download this transactions

**Comment by yasegor** [comment]
Можна більше інформації про таск?

**Comment by YevhenVovk1992** [comment]
Да, хотелось бы хоть какое-то описание.

**Comment by YevhenVovk1992** [comment]
Уникальная транзакция - это та что повторяется только 1 раз?

**Comment by SergeyKutsko** [comment]
> Уникальная транзакция - это та что повторяется только 1 раз? 

Так, ми викачуемо файли у форматі .csv в яких є транзакції але вони можуть повторюватися у різних файлах нам потрібно зберігати тільки унікальні транзакції

**Comment by toxa1818** [comment]
I am taking this task

**Comment by yasegor** [comment]
Беру завдання.

**Comment by toxa1818** [comment]
Правильно ли я понял? Необходимо взять все файлы с транзакциями, и потом все уникальные транзакции собрать в один файл и сохранить в базе. Правильно?

**Comment by botonojke** [comment]
I am taking this task

**Comment by SergeyKutsko** [comment]
> Правильно ли я понял? Необходимо взять все файлы с транзакциями, и потом все уникальные транзакции собрать в один файл и сохранить в базе. Правильно?
> 
> 

Нет просто сохранить файли в одной таблице а уникальные транзакции во второй таблице

**Comment by botonojke** [comment]
> > Правильно ли я понял? Необходимо взять все файлы с транзакциями, и потом все уникальные транзакции собрать в один файл и сохранить в базе. Правильно?
> 
> Нет просто сохранить файли в одной таблице а уникальные транзакции во второй таблице

Что считается уникальной транзакцией ?

**Comment by SergeyKutsko** [comment]
> > > Правильно ли я понял? Необходимо взять все файлы с транзакциями, и потом все уникальные транзакции собрать в один файл и сохранить в базе. Правильно?
> > 
> > 
> > Нет просто сохранить файли в одной таблице а уникальные транзакции во второй таблице
> 
> Что считается уникальной транзакцией ?

Ви коли платите за Uber це унікальна транзакція
