### ISSUE TITLE
Build Django dashboard to Add Drivers, Fleet identifiers and Driver rates

### ISSUE THREAD

**Issue by SergeyKutsko** [SergeyKutsko/universal_auto#6]
Build Django dashboard to Add Drivers, Vendors identifiers and Driver rates to replace static mappings

```
drivers_maps = {
      "uber": {
        "key": "driver_uuid",
         "values": ['775f8943-b0ca-4079-90d3-c81d6563d0f1', '9a182345-fd18-490f-a908-94f520a9d2d1', 'cd725b41-9e47-4fd0-8a1f-3514ddf6238a']
      },
      "bolt": {
        "key": "mobile_number",
        "values": ['+380661891408', '+380936503350', '+380668914200', '+380502428878', '+380671887096']
      },
      "uklon": {
        "key": "signal",
        "values": ['324460', '362612', '372353', '372350', '357339']
      },
      "drivers": {
        'Олександр Холін':   ['775f8943-b0ca-4079-90d3-c81d6563d0f1', '372353', '+380661891408'],
        'Анатолій Мухін':    ['9a182345-fd18-490f-a908-94f520a9d2d1', '362612', '+380936503350'],
        'Сергій Желамський': ['cd725b41-9e47-4fd0-8a1f-3514ddf6238a', '372350', '+380668914200'],
        'Олег Філіппов':     ['d303a6c5-56f7-4ebf-a341-9cfa7c759388', '324460', '+380671887096'],
        'Юрій Філіппов':     ['9c7eb6cb-34e8-46a2-b55b-b41657878376', '357339', '+380502428878']
      },
      "rates": {
        'Олександр Холін':   {"uber": 0.50, "bolt": 0.50, "uklon": 0.50},
        'Анатолій Мухін':    {"uber": 0.65, "bolt": 0.65, "uklon": 0.35},
        'Сергій Желамський': {"uber": 0.50, "bolt": 0.50, "uklon": 0.50},
        'Олег Філіппов':     {"uber": 0.60, "bolt": 0.60, "uklon": 0.40},
        'Юрій Філіппов':     {"uber": 0.60, "bolt": 0.60, "uklon": 0.40},
      }

    }
```
New database structure
![Fleet](https://user-images.githubusercontent.com/424550/192131547-4d90bceb-2ecb-4265-84f8-46d6858fd9aa.png)

UPDATE:
Drivers table should have uniq columns phone and email with basic validation on DB level

**Comment by zxc322** [comment]
About this task
We dont create a table in datbase for drivers?
All we need to do is a fill drivers_maps dict from sashboard?
And what interface expected for a dashboard ( a default django template or...) ?

**Comment by norka2233** [comment]
Taking this task.

**Comment by nyckolas-python** [comment]
Taking this task.

**Comment by SashaBletska** [comment]
I take this task

**Comment by SergeyKutsko** [comment]
> About this task
> 
> We dont create a table in datbase for drivers?
> 
> All we need to do is a fill drivers_maps dict from sashboard?
> 
> And what interface expected for a dashboard ( a default django template or...) ?
> 
We need all hard coded data to tables and add ability to manage it via admin panel

**Comment by SergeyKutsko** [comment]
> About this task
> 
> We dont create a table in datbase for drivers?
> 
> All we need to do is a fill drivers_maps dict from sashboard?
> 
> And what interface expected for a dashboard ( a default django template or...) ?
> 
> default Django template is okay

**Comment by zxc322** [comment]
> > About this task
> > We dont create a table in datbase for drivers?
> > All we need to do is a fill drivers_maps dict from sashboard?
> > And what interface expected for a dashboard ( a default django template or...) ?
> 
> We need all hard coded data to tables and add ability to manage it via admin panel

Okay, so database needed. Got it

**Comment by zxc322** [comment]
Emmm, may I still take this task? :D

**Comment by zxc322** [comment]
> > Emmm, may I still take this task? :D
> 
> As exception yes, but you also will need take another one.

Ok..)

**Comment by pythogoras** [comment]
я так розумію, що пролітаю з цим завданням. чи ще можно?

**Comment by zxc322** [comment]
Hello, have a few questions

- We dont calculating a drivers rate,  we just set it into model, right? So model may look like this 
```
class Driver(models.Model):
    full_name = models.CharField(max_length=24)
    driver_uuid = models.UUIDField(default=uuid.uuid4())
    mobile_number = models.CharField(max_length=13)
    signal = models.CharField(max_length=8)
    uber_rate = models.DecimalField(decimal_places=2, max_digits=3, default=0)   
    uklon_rate = models.DecimalField(decimal_places=2, max_digits=3, default=0)
    bolt_rate = models.DecimalField(decimal_places=2, max_digits=3, default=0)
    deleted_at = models.DateTimeField(null=True, blank=True)

    def __str__(self) -> str:
        return f'{self.id} {self.full_name}'
```

- All we need to changes its add model and use it in  app.libs.selenium_tools.get_report instead off drivers_maps dict?
- Now when Im runing next command with data from model I have the same result as had before with drivers_maps. But maybe some1 have some advices how to test it and where I can find some bugs?
```
python3 manage.py runscript weekly
```

**Comment by SergeyKutsko** [comment]
> Hello, have a few questions
> 
> 
> 
> - We dont calculating a drivers rate,  we just set it into model, right? So model may look like this 
> 
> ```
> 
> class Driver(models.Model):
> 
>     full_name = models.CharField(max_length=24)
> 
>     driver_uuid = models.UUIDField(default=uuid.uuid4())
> 
>     mobile_number = models.CharField(max_length=13)
> 
>     signal = models.CharField(max_length=8)
> 
>     uber_rate = models.DecimalField(decimal_places=2, max_digits=3, default=0)   
> 
>     uklon_rate = models.DecimalField(decimal_places=2, max_digits=3, default=0)
> 
>     bolt_rate = models.DecimalField(decimal_places=2, max_digits=3, default=0)
> 
>     deleted_at = models.DateTimeField(null=True, blank=True)
> 
> 
> 
>     def __str__(self) -> str:
> 
>         return f'{self.id} {self.full_name}'
> 
> ```
> 
> 
> 
> - All we need to changes its add model and use it in  app.libs.selenium_tools.get_report instead off drivers_maps dict?
> 
> - Now when Im runing next command with data from model I have the same result as had before with drivers_maps. But maybe some1 have some advices how to test it and where I can find some bugs?
> 
> ```
> 
> python3 manage.py runscript weekly
> 
> ```
> 
> 

Yes, looks good, if find a bug create a ticket

**Comment by pythogoras** [comment]
Доброго дня. А last_name та first_name не буде? Я бачив в моделі UberPaymentsOrder такі поля то подумав що тоє імя та прізвище водія

**Comment by SergeyKutsko** [comment]
> Доброго дня. А last_name та first_name не буде? Я бачив в моделі UberPaymentsOrder такі поля то подумав що тоє імя та прізвище водія

Так і є це ім'я водія

**Comment by zxc322** [comment]
> Доброго дня. А last_name та first_name не буде? Я бачив в моделі UberPaymentsOrder такі поля то подумав що тоє імя та прізвище водія

Так, але модель Driver та модель UberPaymentsOrder  ми зв'язуємо через поле `driver_uuid`, Driver та Болт по `mobile_number` а Driver та Уклон по `signal`. Виходить що поле з ім'ям в Driver нам треба тільки для формування  репорта в selenium_tools, якщо я все правильно зрозумів. І якщо так то поле full_name трохи зручніше використовувати

**Comment by pythogoras** [comment]
> > Доброго дня. А last_name та first_name не буде? Я бачив в моделі UberPaymentsOrder такі поля то подумав що тоє імя та прізвище водія
> 
> Так, але модель Driver та модель UberPaymentsOrder ми зв'язуємо через поле `driver_uuid`, Driver та Болт по `mobile_number` а Driver та Уклон по `signal`. Виходить що поле з ім'ям в Driver нам треба тільки для формування репорта в selenium_tools, якщо я все правильно зрозумів. І якщо так то поле full_name трохи зручніше використовувати

тоді яке занчення повинно бути в full_name? імя та прізвище?

**Comment by pythogoras** [comment]
> > Доброго дня. А last_name та first_name не буде? Я бачив в моделі UberPaymentsOrder такі поля то подумав що тоє імя та прізвище водія
> 
> Так, але модель Driver та модель UberPaymentsOrder ми зв'язуємо через поле `driver_uuid`, Driver та Болт по `mobile_number` а Driver та Уклон по `signal`. Виходить що поле з ім'ям в Driver нам треба тільки для формування репорта в selenium_tools, якщо я все правильно зрозумів. І якщо так то поле full_name трохи зручніше використовувати

Все ж таки мабудь ти маєш рацію. Доречі SergeyKutsko писав що повинні бути моделі Drivers, Rates та Vendor.

**Comment by zxc322** [comment]
> 

В моєму нинішньому варіанті так, ім'я та прізвище. Та це не так критично,  просто якщо робити first_name + last_name то в  get_report треба буде вказувати `name=first_name+last_name`. І потім `totals[name] = ...`

**Comment by zxc322** [comment]
> > > Доброго дня. А last_name та first_name не буде? Я бачив в моделі UberPaymentsOrder такі поля то подумав що тоє імя та прізвище водія
> > 
> > 
> > Так, але модель Driver та модель UberPaymentsOrder ми зв'язуємо через поле `driver_uuid`, Driver та Болт по `mobile_number` а Driver та Уклон по `signal`. Виходить що поле з ім'ям в Driver нам треба тільки для формування репорта в selenium_tools, якщо я все правильно зрозумів. І якщо так то поле full_name трохи зручніше використовувати
> 
> Все ж таки мабудь ти маєш рацію. Доречі SergeyKutsko писав що повинні бути моделі Drivers, Rates та Vendor.

Хмм..цікаво. Поки що не сильно розумію як це має бути реалізовано і чи потрібно це для виконання саме цього завдання

**Comment by pythogoras** [comment]
> > 
> 
> В моєму нинішньому варіанті так, ім'я та прізвище. Та це не так критично, просто якщо робити first_name + last_name то в get_report треба буде вказувати `name=first_name+last_name`. І потім `totals[name] = ...`

якщо комбінація 'first_name+last_name' в коді застосовується один раз то можно 'totals[first_name+last_name]'

**Comment by zxc322** [comment]
> нь

Ну або в моделі вказати `full_name` xD

**Comment by zxc322** [comment]
Не розумію як добавити рев'ювера в пул_реквест. Хтось робив вже це раніше? Може підказати?

**Comment by SergeyKutsko** [comment]
> Не розумію як добавити рев'ювера в пул_реквест. Хтось робив вже це раніше? Може підказати?

![image](https://user-images.githubusercontent.com/424550/192111697-6a4e63b9-f1df-4807-8e1c-2ba3de808e03.png)

**Comment by pythogoras** [comment]
> Build Django dashboard to Add Drivers, Vendors identifiers and Driver rates to replace static mappings
> 
> ```
> drivers_maps = {
>       "uber": {
>         "key": "driver_uuid",
>          "values": ['775f8943-b0ca-4079-90d3-c81d6563d0f1', '9a182345-fd18-490f-a908-94f520a9d2d1', 'cd725b41-9e47-4fd0-8a1f-3514ddf6238a']
>       },
>       "bolt": {
>         "key": "mobile_number",
>         "values": ['+380661891408', '+380936503350', '+380668914200', '+380502428878', '+380671887096']
>       },
>       "uklon": {
>         "key": "signal",
>         "values": ['324460', '362612', '372353', '372350', '357339']
>       },
>       "drivers": {
>         'Олександр Холін':   ['775f8943-b0ca-4079-90d3-c81d6563d0f1', '372353', '+380661891408'],
>         'Анатолій Мухін':    ['9a182345-fd18-490f-a908-94f520a9d2d1', '362612', '+380936503350'],
>         'Сергій Желамський': ['cd725b41-9e47-4fd0-8a1f-3514ddf6238a', '372350', '+380668914200'],
>         'Олег Філіппов':     ['d303a6c5-56f7-4ebf-a341-9cfa7c759388', '324460', '+380671887096'],
>         'Юрій Філіппов':     ['9c7eb6cb-34e8-46a2-b55b-b41657878376', '357339', '+380502428878']
>       },
>       "rates": {
>         'Олександр Холін':   {"uber": 0.50, "bolt": 0.50, "uklon": 0.50},
>         'Анатолій Мухін':    {"uber": 0.65, "bolt": 0.65, "uklon": 0.35},
>         'Сергій Желамський': {"uber": 0.50, "bolt": 0.50, "uklon": 0.50},
>         'Олег Філіппов':     {"uber": 0.60, "bolt": 0.60, "uklon": 0.40},
>         'Юрій Філіппов':     {"uber": 0.60, "bolt": 0.60, "uklon": 0.40},
>       }
> 
>     }
> ```
> 
> New database structure ![Fleet](https://user-images.githubusercontent.com/424550/192131547-4d90bceb-2ecb-4265-84f8-46d6858fd9aa.png)

які звязки між моделями мають бути?

**Comment by pythogoras** [comment]
> > Build Django dashboard to Add Drivers, Vendors identifiers and Driver rates to replace static mappings
> > ```
> > drivers_maps = {
> >       "uber": {
> >         "key": "driver_uuid",
> >          "values": ['775f8943-b0ca-4079-90d3-c81d6563d0f1', '9a182345-fd18-490f-a908-94f520a9d2d1', 'cd725b41-9e47-4fd0-8a1f-3514ddf6238a']
> >       },
> >       "bolt": {
> >         "key": "mobile_number",
> >         "values": ['+380661891408', '+380936503350', '+380668914200', '+380502428878', '+380671887096']
> >       },
> >       "uklon": {
> >         "key": "signal",
> >         "values": ['324460', '362612', '372353', '372350', '357339']
> >       },
> >       "drivers": {
> >         'Олександр Холін':   ['775f8943-b0ca-4079-90d3-c81d6563d0f1', '372353', '+380661891408'],
> >         'Анатолій Мухін':    ['9a182345-fd18-490f-a908-94f520a9d2d1', '362612', '+380936503350'],
> >         'Сергій Желамський': ['cd725b41-9e47-4fd0-8a1f-3514ddf6238a', '372350', '+380668914200'],
> >         'Олег Філіппов':     ['d303a6c5-56f7-4ebf-a341-9cfa7c759388', '324460', '+380671887096'],
> >         'Юрій Філіппов':     ['9c7eb6cb-34e8-46a2-b55b-b41657878376', '357339', '+380502428878']
> >       },
> >       "rates": {
> >         'Олександр Холін':   {"uber": 0.50, "bolt": 0.50, "uklon": 0.50},
> >         'Анатолій Мухін':    {"uber": 0.65, "bolt": 0.65, "uklon": 0.35},
> >         'Сергій Желамський': {"uber": 0.50, "bolt": 0.50, "uklon": 0.50},
> >         'Олег Філіппов':     {"uber": 0.60, "bolt": 0.60, "uklon": 0.40},
> >         'Юрій Філіппов':     {"uber": 0.60, "bolt": 0.60, "uklon": 0.40},
> >       }
> > 
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > New database structure ![Fleet](https://user-images.githubusercontent.com/424550/192131547-4d90bceb-2ecb-4265-84f8-46d6858fd9aa.png)
> 
> які звязки між моделями мають бути?

один_з_одним, один_з_багатьма, багато_з_батьма? P.S. Розумію, що питання звучить десь еротично))

**Comment by zxc322** [comment]
Доброго ранку, чи правильно я розумію ща `rate` в моделях ордерів, тут наприклад 
```
def report_text(self, name = None, rate = 0.65):
        name = name or f'{self.first_name} {self.last_name}'
```
має братися з моделі `Fleet` з поля 'fees`. Якшо ні то дк ми використовуємо цей fees
І ще ми все одно беремо для розрахунку репорта rate конкретного водія, а в моделі це захардкожене число
Хтось розбирався вже? Які думки маєте

**Comment by SergeyKutsko** [comment]
Рейтинг потрібно брати з таблиці _rates

**Comment by zxc322** [comment]
так, побачив

**Comment by pythogoras** [comment]
> Build Django dashboard to Add Drivers, Vendors identifiers and Driver rates to replace static mappings
> 
> ```
> drivers_maps = {
>       "uber": {
>         "key": "driver_uuid",
>          "values": ['775f8943-b0ca-4079-90d3-c81d6563d0f1', '9a182345-fd18-490f-a908-94f520a9d2d1', 'cd725b41-9e47-4fd0-8a1f-3514ddf6238a']
>       },
>       "bolt": {
>         "key": "mobile_number",
>         "values": ['+380661891408', '+380936503350', '+380668914200', '+380502428878', '+380671887096']
>       },
>       "uklon": {
>         "key": "signal",
>         "values": ['324460', '362612', '372353', '372350', '357339']
>       },
>       "drivers": {
>         'Олександр Холін':   ['775f8943-b0ca-4079-90d3-c81d6563d0f1', '372353', '+380661891408'],
>         'Анатолій Мухін':    ['9a182345-fd18-490f-a908-94f520a9d2d1', '362612', '+380936503350'],
>         'Сергій Желамський': ['cd725b41-9e47-4fd0-8a1f-3514ddf6238a', '372350', '+380668914200'],
>         'Олег Філіппов':     ['d303a6c5-56f7-4ebf-a341-9cfa7c759388', '324460', '+380671887096'],
>         'Юрій Філіппов':     ['9c7eb6cb-34e8-46a2-b55b-b41657878376', '357339', '+380502428878']
>       },
>       "rates": {
>         'Олександр Холін':   {"uber": 0.50, "bolt": 0.50, "uklon": 0.50},
>         'Анатолій Мухін':    {"uber": 0.65, "bolt": 0.65, "uklon": 0.35},
>         'Сергій Желамський': {"uber": 0.50, "bolt": 0.50, "uklon": 0.50},
>         'Олег Філіппов':     {"uber": 0.60, "bolt": 0.60, "uklon": 0.40},
>         'Юрій Філіппов':     {"uber": 0.60, "bolt": 0.60, "uklon": 0.40},
>       }
> 
>     }
> ```
> 
> New database structure ![Fleet](https://user-images.githubusercontent.com/424550/192131547-4d90bceb-2ecb-4265-84f8-46d6858fd9aa.png)

dev_maps це сформовані данні які треба внести в БД? Якщо так, тоді якщо припустити що в rates будуть однакові імя та прізвище, як зрозуміти до якого водія відноситься rate?

**Comment by zxc322** [comment]
у кожного водiя свiй id. У таблиці справа ми використовуємо ForeignKey. Можемо отримати всіх водіїв в змінну `drivers`
```
  for deiver in drivers:
    Rates.objects.get(fleet__name='Uber', driver=driver)
``` 
Приблизно так я думаю

**Comment by pythogoras** [comment]
> у кожного водiя свiй id. У таблиці справа ми використовуємо ForeignKey. Можемо отримати всіх водіїв в змінну `drivers`
> 
> ```
>   for deiver in drivers:
>     Rates.objects.get(fleet__name='Uber', driver=driver)
> ```
> 
> Приблизно так я думаю

але в fleet_name вказаний тип int

**Comment by pythogoras** [comment]
> > у кожного водiя свiй id. У таблиці справа ми використовуємо ForeignKey. Можемо отримати всіх водіїв в змінну `drivers`
> > ```
> >   for deiver in drivers:
> >     Rates.objects.get(fleet__name='Uber', driver=driver)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Приблизно так я думаю
> 
> але в fleet__name вказаний тип int

**Comment by pythogoras** [comment]
> > > > у кожного водiя свiй id. У таблиці справа ми використовуємо ForeignKey. Можемо отримати всіх водіїв в змінну `drivers`
> > > > ```
> > > >   for deiver in drivers:
> > > >     Rates.objects.get(fleet__name='Uber', driver=driver)
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Приблизно так я думаю
> > > 
> > > 
> > > але в fleet__name вказаний тип int
> 
> тоді виникає ще питання - якщо поле name унікальне то може замінити їм поле id?

поле name моделі fleets

**Comment by zxc322** [comment]
> > > > > у кожного водiя свiй id. У таблиці справа ми використовуємо ForeignKey. Можемо отримати всіх водіїв в змінну `drivers`
> > > > > ```
> > > > >   for deiver in drivers:
> > > > >     Rates.objects.get(fleet__name='Uber', driver=driver)
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > Приблизно так я думаю
> > > > 
> > > > 
> > > > але в fleet__name вказаний тип int
> > 
> > 
> > тоді виникає ще питання - якщо поле name унікальне то може замінити їм поле id?
> 
> поле name моделі fleets

Хмм, цікаво. З джанго це трохи напряжно напевно) Ми не вказуємо поле id(prymary_key) в моделі явно, джанго сам його створює. Я колись робив ще поле SlugField, яке при створенні об'єкта через адмінку генерувалось так ж саме як ім'я і воно мало бути унікальним. І потім звертався в базу по цьому слагу. Але ID при цьому створювався сам, хоть я його і не використовував. Можна погуглить...

**Comment by zxc322** [comment]
Поле `fees` моделі `Fleets`. Де брати ці значення і де в коді будемо використовувати? Поки що ніде не бачу

**Comment by zxc322** [comment]
У моделі з ids_and_rates одне з полів `vehicles`. 
Це поле може бути blank=True, null=True? Якшо ні то де брати дані для цієї моделі?

**Comment by SergeyKutsko** [comment]
@zxc322 venicle_id can't be blank

**Comment by SergeyKutsko** [comment]
> У моделі з ids_and_rates одне з полів `vehicles`. Це поле може бути blank=True, null=True? Якшо ні то де брати дані для цієї моделі?
venicle_id should be taken from venicles table

**Comment by SergeyKutsko** [comment]
> Поле `fees` моделі `Fleets`. Де брати ці значення і де в коді будемо використовувати? Поки що ніде не бачу

Uber = 22%
Bolt = 25 %
Uklon = 17%

Це для фнформаціі в розрахунках не використовуеться

**Comment by zxc322** [comment]
If we want unique car for every driver, so maybe better choise will be use vihecle_id in Driver model?
```
class Driver(models.Model):
    full_name = models.CharField(max_length=24)
    vehicle = models.OneToOneField('Vehicles', on_delete=models.CASCADE)
    created_ad = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    def __str__(self) -> str:
        return self.full_name
```        
What do you think?

**Comment by SergeyKutsko** [comment]
No car can belong to one driver today but to other driver next day. And we
need keep history of that to be able calculate salary , since electric car
has different rate than diesel

Чт, 29 сент. 2022 г. в 09:18, zxc_322 ***@***.***>:

**Comment by zxc322** [comment]
> e car for every driver, so maybe better choise will be use vihecle_id in Driver model?
> 
> ```
> class Driver(models.Mode
> ```

Okay, so another question. If driver hase unique ids in at least 2 fleets ( Bolt + Uber) he must have 2 different cars for that. Other wise we got this error
![Screenshot (9)](https://user-images.githubusercontent.com/91989456/192955413-a0f7c4dd-e54a-4caa-8437-8a912dcbd81b.png)

**Comment by zxc322** [comment]
> > e car for every driver, so maybe better choise will be use vihecle_id in Driver model?
> > ```
> > class Driver(models.Mode
> > ```
> 
> Okay, so another question. If driver hase unique ids in at least 2 fleets ( Bolt + Uber) he must have 2 different cars for that. Other wise we got this error ![Screenshot (9)](https://user-images.githubusercontent.com/91989456/192955413-a0f7c4dd-e54a-4caa-8437-8a912dcbd81b.png)

with this code I mean
```
class Fleets_Drivers_Vehicles_Rate(models.Model):
    fleet = models.ForeignKey(Fleet, on_delete=models.CASCADE)
    driver = models.ForeignKey(Driver, on_delete=models.CASCADE)
    vehicle = models.OneToOneField(Vehicles, on_delete=models.CASCADE)
    driver_external_id = models.CharField(max_length=200)
    rate = models.DecimalField(decimal_places=2, max_digits=3, default=0)
    created_ad = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    def __str__(self) -> str:
        return self.driver_external_id
        
```

**Comment by zxc322** [comment]
Nevermind, i think I know how resolve it)

**Comment by SergeyKutsko** [comment]
> > e car for every driver, so maybe better choise will be use vihecle_id in Driver model?
> 
> > 
> 
> > ```
> 
> > class Driver(models.Mode
> 
> > ```
> 
> 
> 
> Okay, so another question. If driver hase unique ids in at least 2 fleets ( Bolt + Uber) he must have 2 different cars for that. Other wise we got this error
> 
> ![Screenshot (9)](https://user-images.githubusercontent.com/91989456/192955413-a0f7c4dd-e54a-4caa-8437-8a912dcbd81b.png)
> 
> 

You are right so no need add uniq , since whole history will saved in this table, last record per fleet for each driver should be considered as current active rate for fleet and car

**Comment by zxc322** [comment]
> You are right so no need add uniq

Oh, rly? Ok than ( I arldy found another solution with using unique value) .
Then I set vehicle as FK field

**Comment by nyckolas-python** [comment]
In the Fleets model
the name field must be unique?

shouldn't be Uber and Uber but with different fees?

**Comment by SergeyKutsko** [comment]
@

> In the Fleets model the name field must be unique?
> 
> shouldn't be Uber and Uber but with different fees?

yes, name is uniq.

**Comment by pythogoras** [comment]
а чому Drivers привязати до Venicles?

**Comment by pythogoras** [comment]
в мене відверто кажучи вже фантазії не вистачає окрім як лізти в FrontEnd admin панелі.
