### ISSUE TITLE
Add identification by mobile number to telegram bot and config access rules for roles Driver, Owner, Manager

### ISSUE THREAD

**Issue by SergeyKutsko** [SergeyKutsko/universal_auto#7]
Вам потрібно створити модель в базі даних це може бути  з назвою User, але треба її зробити такою, щоб в нас були різні типи Users тобто в нас буде User який Driver юзер який Manager і юзер який Owner у них повинно бути таке поле яке буде зазначати який це саме тип ми зберігаємо так звану Single Table Inheritance  підхід до розробки моделей це коли в одній таблиці зберігаються 
об'єкти типів шо можуть наслідувати більшу кількість атрибутів  Ось в коді це будуть різні моделі з різним ім'ям, але таблиці у них буде тільки одне поле різне з типом моделі 
 
Дуже важливо зберігати chat_id   
який приходить 
коли юзер починає роботу з ботом цей chat_id потрібен, щоб відсилати меседжі назад

**Comment by MakarSerhii** [comment]
I take this task

**Comment by pythogoras** [comment]
I take this task

**Comment by polinamalyhina** [comment]
Me either

**Comment by OlegBondarUA** [comment]
I take this task

**Comment by SergeyKutsko** [comment]
@OlegBondarUA please add this code here:
https://github.com/SergeyKutsko/universal_auto/blob/develop/scripts/bot.py
