### ISSUE TITLE
Add a new field to the Fleets_drivers_vehicles_rate model. This field: can the driver withdraw money from the fleet account. Only for Uklon

### ISSUE THREAD

**Issue by bogdannoff** [SergeyKutsko/universal_auto#76]
Set the value to DB when getting the weekly report. Set value for Uklon site when it changes in DB. Use Selenium

**Comment by YevhenVovk1992** [comment]
Can I try do this task?

**Comment by YevhenVovk1992** [comment]
When I try to get a report, I get an error. As if there is no migration

**Comment by SpaceIgor** [comment]
> When I try to get a report, I get an error. I made a migration. Got a report. I just haven't figured out what it is yet. Now I can start editing the model?

можно скрін помилки ?

**Comment by SpaceIgor** [comment]
@YevhenVovk1992 скрін помилки можно?

**Comment by YevhenVovk1992** [comment]
Model Fleets_drivers_vehicles_rate is having  withdraw_money column. Should i add new column like withdraw_money_from account?

**Comment by SpaceIgor** [comment]
> Model Fleets_drivers_vehicles_rate is having withdraw_money column. Should i add new column like withdraw_money_from account?

@YevhenVovk1992 u need.Set the value to DB when getting the weekly report. Set value for Uklon site when it changes in DB. Use Seleniu. Pls use @ for communication

**Comment by YevhenVovk1992** [comment]
@SpaceIgor Can you help me? When I run "docker exec -it universal_auto_web python3 manage.py runscript weekly"б I get in the console "({'Fleet Owner': 0}, {})". why can't I get the report?

Where do you get the value that you need to specify in order to save the model?

**Comment by SpaceIgor** [comment]
@YevhenVovk1992  pull develop. Change in bot.py in func report DEVELOPER_CHAT_ID on your chat_id and run /report and u see report in bot
