### ISSUE TITLE
Create Fake Uber service to make end-to-end testing possible in dev ENVs

### ISSUE THREAD

**Issue by SergeyKutsko** [SergeyKutsko/universal_auto#8]
The fake service should be a part of a current Django application, and it should mimic the original, so we can run the report the same way as on production and receive a report.

Authentication page with login and password can be copied from https://drivers.uber.com/

Here is an example of report page:

[Archive 4.zip](https://github.com/SergeyKutsko/universal_auto/files/9638066/Archive.4.zip)

**Comment by SergeyKutsko** [comment]
Authentication page with login and password can be copied from https://drivers.uber.com/

**Comment by Mr-Furman** [comment]
Беру це завдання.

**Comment by SergeyKutsko** [comment]
> Беру це завдання.

Cool
