### ISSUE TITLE
Implement status sync service for Bolt

### ISSUE THREAD

**Issue by SergeyKutsko** [SergeyKutsko/universal_auto#84]
<img width="1772" alt="Screenshot 2022-12-11 at 12 14 37" src="https://user-images.githubusercontent.com/424550/206897924-e304b827-00e0-459a-bc62-417d34afbb76.png">
We need to pull real time bolt status per driver and save it to DB to have global status across all Fleets to have ability connect Free online drivers with Clients of Universal Auto Taxi.
https://fleets.bolt.eu/v2/58225/liveMap

**Comment by bogdannoff** [comment]
done
