### ISSUE TITLE
Create Fake Uklon service to make end-to-end testing possible in dev ENVs

### ISSUE THREAD

**Issue by SergeyKutsko** [SergeyKutsko/universal_auto#9]
The fake service should be a part of a current Django application, and it should mimic the original, so we can run the report the same way as on production and receive a report. 

Authentication page with login and password can be copied from https://partner.uklon.com.ua/

Here is an example of report page:

[Archive 3.zip](https://github.com/SergeyKutsko/universal_auto/files/9638046/Archive.3.zip)

**Comment by SergeyKutsko** [comment]
Authentication page with login and password can be copied from https://partner.uklon.com.ua/

**Comment by alex2011ua** [comment]
Тобто потрібно додати django application та в ньому створити Fake Uklon?

**Comment by SergeyKutsko** [comment]
@alex2011ua you can use current Django app to create Fake Uklon

**Comment by alex2011ua** [comment]
I wish take this issue.

**Comment by alex2011ua** [comment]
I have done part of work, but i didn't have  permission to create and push new branch,

**Comment by SergeyKutsko** [comment]
@alex2011ua fork and make PR

**Comment by SergeyKutsko** [comment]
Fork project and make PR

сб, 24 сент. 2022 г. в 10:00, alex2011ua ***@***.***>:

**Comment by alex2011ua** [comment]
I must make PR to your prodject or to my fork prodject?

**Comment by SergeyKutsko** [comment]
@alex2011ua pr to my  github project
